#!/usr/bin/python3

import fire
import random
import string
from tkinter import *
import tkinter.ttk as ttl
from tkinter.font import *

def gen(length = 16):
    if type(length) == str:
        length = len(length)
    result = ''.join(random.choices(string.ascii_letters, k=length))
    return result
def graphic():
    root = Tk()
    root.geometry("800x600")
    root.title("rstring")

    root.grid_columnconfigure(0, weight=1)

    f = Font(size=20, family="Roboto")

    Label(root, text="rstring", font=f).grid(row=0)
    Label(root, text="Length: ").grid(row=1)
    lengthEntry = Entry(root)
    lengthEntry.grid(row=2)
    genLabel = Label()
    genLabel.grid(row=4)
    def copy_text_to_clipboard(txt):
       root.clipboard_clear()
       root.clipboard_append(txt)
    def genLabelfun(length):
        global gResult
        gResult = ''.join(random.choices(string.ascii_letters, k=length))
        genLabel.config(text=gResult)
    Button(root, text="Generate", command=lambda:genLabelfun(int(lengthEntry.get()))).grid(row=3)
    Button(root, text="Copy To Clipboard", command=lambda:copy_text_to_clipboard(gResult)).grid(row=5)

    root.mainloop()

if __name__ == '__main__':
    fire.Fire()
